### ISSUE TITLE
How to know when the SSE session gets closed?

### ISSUE THREAD

**Issue by specimen151** [toverux/expresse#3]
I'm using the simple form

        this.router.get('/:id/events', sse(), (req,res:ISseResponse) => { 
               someModule.on('someEvent', (event) => 

And what happens is that when I reload my client page a couple of times, the number of event listeners keep adding up (from the `someModule.on`). 

I can't depend on clients properly calling some "unregister" url, so I'm wondering if there's any way to detect clients which are no longer listening for SSE?

**Comment by specimen151** [comment]
Sorry about the title. I'm not dating there is a bug or anything, just that by following the example I end up with a lot of events internally on the server (by reloading the client several times, new subscriptions are made) because I don't know how to detect when the client has left.

**Comment by toverux** [comment]
Hi @specimen151, fortunately this part of ExpreSSE can help you: [src/sse_handler_middleware.ts#L40-L42](https://github.com/toverux/expresse/blob/master/src/sse_handler_middleware.ts#L40-L42)

As you can see, it's used here to clear the keepalive interval when the client (or the server) closes the connection by closing the tab (or when res.end() is called on the server). _(Amusingly, this is the reason that got me releasing ExpreSSE. I've first used an SSE package that was not clearing the interval for keepalives, meaning that a high traffic would lead to massive event loop overloading and memory leaks.)_

I let you close this if everything is good. By the way, this makes me think that I could add a feature so that ExpreSSE can take a callback to invoke when the session gets closed.

**Comment by specimen151** [comment]
Thank you, this works perfectly!!

For others' benefit, here's a full example (excerpt):

    this.router.get('/:id/events', sse(), (req,res:ISseResponse) => {
            // now we have a stream open with the client, it's going to stay open until client closes it (or misses heartbeat)
            res.sse.event('subscribe',{message:'You are now listening for events for CarePlan '+req.params.id})

            // keep the callback as a variable, for use with the unsubscribe
            // declare the callback inline here, as a closure, to get to use the req/res variables
            var callback = (e)=> {
                console.log('Incoming event',e)
                res.sse.event('update',{.....})         
            }
            this.emitter.on('update',callback)   // subscribe to events internal on the server
            res.once('close', () => { // when client closes connection, unsubscribe from internal events on server
                console.log('connection closed from client')
                this.emitter.removeListener('update',callback)
            });
            res.once('finish', () =>  { /* same here -- unsubscribe*/ });
        }),
